version: '3.9'

services:
  api:
    container_name: api
    image: ./
    ports:
      - "5000:80"
    depends_on:
      - db
  
  db:
    container_name: database
    image: ./dockerfile_db
    ports:
      - "1433:1433"

networks:
  default:
    name: GeoPet_net