name: Staging

on:
  pull_request:
    types: [opened, synchronize]
    branches: [ "staging" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3

      - name: Teste application
        run: dotnet test tests